### ISSUE TITLE
Branch updates

### ISSUE THREAD

**Issue by marekhrabe** [Automattic/calypso-live-branches#3]
How does calypso.live behave when someone pushes to a branch that was previously booted? Does it pull changes or stays the same? 

Can we add current commit hash somewhere on the page? Env badge, just next to the branch name, would seem like a good place for me

**Comment by Tug** [comment]
> How does calypso.live behave when someone pushes to a branch that was previously booted? Does it pull changes or stays the same?

So the way it works at the moment is that, on every new request to a booted branch, it's going to:
- check if the branch is up to date with the mirror repository (which is synchronized with github every minutes)
- if it's up to date, it will just forward the request to the correct server instance.
- if it's not up to date, it's going to update the branch first, then check if one of the files in the following directories have been modified https://github.com/Automattic/calypso-live-branches/blob/master/calypso.json#L16. If it's the case it will shutdown the current server process and serve the boot page which will reload the app. Otherwise it won't reboot the process since this is a dev environment and webpack-dev-server supports hot reloading.

> Can we add current commit hash somewhere on the page? Env badge, just next to the branch name, would seem like a good place for me

The commit number is already available when hovering the branch name on the badge ;)
